const express = require('express')
const { dbConnection } = require('./db/config')
const cors = require('cors')
require('dotenv').config()
const app = express()
dbConnection()
    //directorio publico
app.use(express.static('public'))
app.use(cors())
app.use(express.json())
app.use('/api/usuarios', require('./routes/usuarios'))
app.use('/api/hospitales', require('./routes/hospitales'))
app.use('/api/medicos', require('./routes/medicos'))
app.use('/api/login', require('./routes/auth'))
app.use('/api/todo', require('./routes/busquedas'))
app.use('/api/upload', require('./routes/uploads'))
    //lectura y parseo del body
app.listen(process.env.PORT, () => {
    console.log('servidor corriendo => ', process.env.PORT)
})